// Code generated by goplus from logger.gp. DO NOT EDIT.
//goplus:v v0.28.0

package middleware

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"runtime"
	"time"
)

type logEntryKey struct{ name string }

func (key *logEntryKey) String() string {
	return "chi/middleware context value " + key.name
}

var LogEntryCtxKey = &logEntryKey{"LogEntry"}

var DefaultLogger func(http.Handler) http.Handler

type LogFormatter interface {
	NewLogEntry(*http.Request) LogEntry
}

type LogEntry interface {
	Write(status, bytes int, header http.Header, elapsed time.Duration, extra any)
	Panic(value any, stack []byte)
}

type LoggerInterface interface {
	Print(...any)
}

func Logger(next http.Handler) http.Handler {
	return DefaultLogger(next)
}

func RequestLogger(formatter LogFormatter) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			entry := formatter.NewLogEntry(r)
			writer := NewWrapResponseWriter(w, r.ProtoMajor)
			started := time.Now()
			defer func() {
				entry.Write(writer.Status(), writer.BytesWritten(), writer.Header(), time.Since(started), nil)
			}()
			next.ServeHTTP(writer, WithLogEntry(r, entry))
		})
	}
}

func GetLogEntry(r *http.Request) LogEntry {
	entry, _ := r.Context().Value(LogEntryCtxKey).(LogEntry)
	return entry
}

func WithLogEntry(r *http.Request, entry LogEntry) *http.Request {
	ctx := context.WithValue(r.Context(), LogEntryCtxKey, entry)
	return r.WithContext(ctx)
}

type DefaultLogFormatter struct {
	Logger  LoggerInterface
	NoColor bool
}

func (formatter *DefaultLogFormatter) NewLogEntry(r *http.Request) LogEntry {
	entry := &defaultLogEntry{
		formatter: formatter,
		request:   r,
		buffer:    &bytes.Buffer{},
		useColor:  !formatter.NoColor,
	}
	if requestID := GetReqID(r.Context()); requestID != "" {
		entry.writeColor("\033[33m", "[%s] ", requestID)
	}
	entry.writeColor("\033[36m", "\"")
	entry.writeColor("\033[35;1m", "%s ", r.Method)
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	entry.writeColor("\033[36m", "%s://%s%s %s\" ", scheme, r.Host, r.RequestURI, r.Proto)
	entry.buffer.WriteString("from ")
	clientIP := GetClientIP(r.Context())
	if clientIP == "" {
		clientIP = r.RemoteAddr
	}
	entry.buffer.WriteString(clientIP)
	entry.buffer.WriteString(" - ")
	return entry
}

type defaultLogEntry struct {
	formatter *DefaultLogFormatter
	request   *http.Request
	buffer    *bytes.Buffer
	useColor  bool
}

func (entry *defaultLogEntry) Write(status, bytes int, _ http.Header, elapsed time.Duration, _ any) {
	color := "\033[31;1m"
	switch {
	case status < 200:
		color = "\033[34;1m"
	case status < 300:
		color = "\033[32;1m"
	case status < 400:
		color = "\033[36;1m"
	case status < 500:
		color = "\033[33;1m"
	}
	entry.writeColor(color, "%03d", status)
	entry.writeColor("\033[34;1m", " %dB", bytes)
	entry.buffer.WriteString(" in ")
	switch {
	case elapsed < 500*time.Millisecond:
		entry.writeColor("\033[32m", "%s", elapsed)
	case elapsed < 5*time.Second:
		entry.writeColor("\033[33m", "%s", elapsed)
	default:
		entry.writeColor("\033[31m", "%s", elapsed)
	}
	entry.formatter.Logger.Print(entry.buffer.String())
}

func (entry *defaultLogEntry) Panic(value any, _ []byte) {
	printPrettyStack(value, entry.useColor)
}

func (entry *defaultLogEntry) writeColor(color, format string, values ...any) {
	if IsTTY && entry.useColor {
		entry.buffer.WriteString(color)
	}
	_, _ = fmt.Fprintf(entry.buffer, format, values...)
	if IsTTY && entry.useColor {
		entry.buffer.WriteString("\033[0m")
	}
}

func init() {
	color := runtime.GOOS != "windows"
	DefaultLogger = RequestLogger(&DefaultLogFormatter{
		Logger:  log.New(os.Stdout, "", log.LstdFlags),
		NoColor: !color,
	})
}
