// Code generated by goplus from transform.gp. DO NOT EDIT.
//goplus:v v0.28.0

package middleware

import (
	"context"
	"crypto/subtle"
	"fmt"
	"net/http"
	"slices"
	"strings"
	"time"
)

func AllowContentEncoding(encodings ...string) func(http.Handler) http.Handler {
	allowed := normalizedSet(encodings)
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.ContentLength != 0 {
				for _, encoding := range r.Header["Content-Encoding"] {
					if _, ok := allowed[normalize(encoding)]; !ok {
						w.WriteHeader(http.StatusUnsupportedMediaType)
						return
					}
				}
			}
			next.ServeHTTP(w, r)
		})
	}
}

func AllowContentType(contentTypes ...string) func(http.Handler) http.Handler {
	allowed := normalizedSet(contentTypes)
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.ContentLength == 0 {
				next.ServeHTTP(w, r)
				return
			}
			contentType, _, _ := strings.Cut(r.Header.Get("Content-Type"), ";")
			if _, ok := allowed[normalize(contentType)]; !ok {
				w.WriteHeader(http.StatusUnsupportedMediaType)
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

func ContentCharset(charsets ...string) func(http.Handler) http.Handler {
	for index := range charsets {
		charsets[index] = strings.ToLower(charsets[index])
	}
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			_, parameters, _ := strings.Cut(strings.ToLower(r.Header.Get("Content-Type")), ";")
			_, charset, _ := strings.Cut(strings.TrimSpace(parameters), "charset=")
			charset, _, _ = strings.Cut(strings.TrimSpace(charset), ";")
			if !slices.Contains(charsets, strings.TrimSpace(charset)) {
				w.WriteHeader(http.StatusUnsupportedMediaType)
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

func SetHeader(key, value string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set(key, value)
			next.ServeHTTP(w, r)
		})
	}
}

func WithValue(key, value any) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			next.ServeHTTP(w, r.WithContext(context.WithValue(r.Context(), key, value)))
		})
	}
}

func RequestSize(bytes int64) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			r.Body = http.MaxBytesReader(w, r.Body, bytes)
			next.ServeHTTP(w, r)
		})
	}
}

func BasicAuth(realm string, credentials map[string]string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			user, password, ok := r.BasicAuth()
			expected, found := credentials[user]
			if !ok || !found || subtle.ConstantTimeCompare([]byte(password), []byte(expected)) != 1 {
				w.Header().Add("WWW-Authenticate", fmt.Sprintf(`Basic realm="%s"`, realm))
				w.WriteHeader(http.StatusUnauthorized)
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

func Maybe(middleware func(http.Handler) http.Handler, when func(*http.Request) bool) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if when(r) {
				middleware(next).ServeHTTP(w, r)
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

var noCacheResponseHeaders = map[string]string{
	"Expires":         time.Unix(0, 0).UTC().Format(http.TimeFormat),
	"Cache-Control":   "no-cache, no-store, no-transform, must-revalidate, private, max-age=0",
	"Pragma":          "no-cache",
	"X-Accel-Expires": "0",
}

var conditionalRequestHeaders = []string{
	"ETag", "If-Modified-Since", "If-Match", "If-None-Match", "If-Range", "If-Unmodified-Since",
}

func NoCache(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		for _, key := range conditionalRequestHeaders {
			r.Header.Del(key)
		}
		for key, value := range noCacheResponseHeaders {
			w.Header().Set(key, value)
		}
		next.ServeHTTP(w, r)
	})
}

func PathRewrite(old, new string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			r.URL.Path = strings.Replace(r.URL.Path, old, new, 1)
			next.ServeHTTP(w, r)
		})
	}
}

func Sunset(at time.Time, links ...string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if !at.IsZero() {
				value := at.Format(http.TimeFormat)
				w.Header().Set("Sunset", value)
				w.Header().Set("Deprecation", value)
				for _, link := range links {
					w.Header().Add("Link", link)
				}
			}
			next.ServeHTTP(w, r)
		})
	}
}

func normalizedSet(values []string) map[string]struct{} {
	set := make(map[string]struct{}, len(values))
	for _, value := range values {
		set[normalize(value)] = struct{}{}
	}
	return set
}

func normalize(value string) string {
	return strings.ToLower(strings.TrimSpace(value))
}
